//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Tb
    {
        public int VehicleID { get; set; }
        public string Model { get; set; }
        public string Engine { get; set; }
        public int H_P { get; set; }
        public string Color { get; set; }
        public int Price { get; set; }
        public string Customer { get; set; }
    }
}
